Proyecto/CamionesFrame/src/java/entity/CamionViaje.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package entity;

import java.io.Serializable;
import java.util.Collection;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 *
 * @author shayde
 */
@Entity
@Table(name = "camion_viaje")
@NamedQueries({
    @NamedQuery(name = "CamionViaje.findAll", query = "SELECT c FROM CamionViaje c"),
    @NamedQuery(name = "CamionViaje.findByIdCamionViaje", query = "SELECT c FROM CamionViaje c WHERE c.idCamionViaje = :idCamionViaje")})
public class CamionViaje implements Serializable {
    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "id_camion_viaje")
    private Integer idCamionViaje;
    @OneToMany(mappedBy = "idCamionViaje")
    private Collection<Boletos> boletosCollection;
    @JoinColumn(name = "id_viaje", referencedColumnName = "id_viaje")
    @ManyToOne
    private Viajes idViaje;
    @JoinColumn(name = "id_camion", referencedColumnName = "id_camion")
    @ManyToOne
    private Camiones idCamion;

    public CamionViaje() {
    }

    public CamionViaje(Integer idCamionViaje) {
        this.idCamionViaje = idCamionViaje;
    }

    public Integer getIdCamionViaje() {
        return idCamionViaje;
    }

    public void setIdCamionViaje(Integer idCamionViaje) {
        this.idCamionViaje = idCamionViaje;
    }

    public Collection<Boletos> getBoletosCollection() {
        return boletosCollection;
    }

    public void setBoletosCollection(Collection<Boletos> boletosCollection) {
        this.boletosCollection = boletosCollection;
    }

    public Viajes getIdViaje() {
        return idViaje;
    }

    public void setIdViaje(Viajes idViaje) {
        this.idViaje = idViaje;
    }

    public Camiones getIdCamion() {
        return idCamion;
    }

    public void setIdCamion(Camiones idCamion) {
        this.idCamion = idCamion;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (idCamionViaje != null ? idCamionViaje.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof CamionViaje)) {
            return false;
        }
        CamionViaje other = (CamionViaje) object;
        if ((this.idCamionViaje == null && other.idCamionViaje != null) || (this.idCamionViaje != null && !this.idCamionViaje.equals(other.idCamionViaje))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "entity.CamionViaje[ idCamionViaje=" + idCamionViaje + " ]";
    }
    
}

Proyecto/CamionesFrame/src/java/controller/CamionViajeController.java
package controller;

import entity.CamionViaje;
import controller.util.JsfUtil;
import controller.util.JsfUtil.PersistAction;
import session.CamionViajeFacade;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;

@Named("camionViajeController")
@SessionScoped
public class CamionViajeController implements Serializable {

    @EJB
    private session.CamionViajeFacade ejbFacade;
    private List<CamionViaje> items = null;
    private CamionViaje selected;

    public CamionViajeController() {
    }

    public CamionViaje getSelected() {
        return selected;
    }

    public void setSelected(CamionViaje selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
    }

    protected void initializeEmbeddableKey() {
    }

    private CamionViajeFacade getFacade() {
        return ejbFacade;
    }

    public CamionViaje prepareCreate() {
        selected = new CamionViaje();
        initializeEmbeddableKey();
        return selected;
    }

    public void create() {
        persist(PersistAction.CREATE, ResourceBundle.getBundle("/Bundle").getString("CamionViajeCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void update() {
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/Bundle").getString("CamionViajeUpdated"));
    }

    public void destroy() {
        if (selected == null) {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Advertencia!", "Seleccione un camión de la lista"));
        } else {
            persist(PersistAction.DELETE, ResourceBundle.getBundle("/Bundle").getString("CamionViajeDeleted"));
            if (!JsfUtil.isValidationFailed()) {
                selected = null; // Remove selection
                items = null;    // Invalidate list of items to trigger re-query.
            }
        }
    }

    public List<CamionViaje> getItems() {
        if (items == null) {
            items = getFacade().findAll();
        }
        return items;
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                } else {
                    getFacade().remove(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            }
        }
    }

    public CamionViaje getCamionViaje(java.lang.Integer id) {
        return getFacade().find(id);
    }

    public List<CamionViaje> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<CamionViaje> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass = CamionViaje.class)
    public static class CamionViajeControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            CamionViajeController controller = (CamionViajeController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "camionViajeController");
            return controller.getCamionViaje(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof CamionViaje) {
                CamionViaje o = (CamionViaje) object;
                return getStringKey(o.getIdCamionViaje());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), CamionViaje.class.getName()});
                return null;
            }
        }

    }

}

Proyecto/CamionesFrame/src/java/controller/ViajesController.java
package controller;

import entity.Viajes;
import controller.util.JsfUtil;
import controller.util.JsfUtil.PersistAction;
import session.ViajesFacade;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;

@Named("viajesController")
@SessionScoped
public class ViajesController implements Serializable {

    @EJB
    private session.ViajesFacade ejbFacade;
    private List<Viajes> items = null;
    private Viajes selected;

    public ViajesController() {
    }

    public Viajes getSelected() {
        return selected;
    }

    public void setSelected(Viajes selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
    }

    protected void initializeEmbeddableKey() {
    }

    private ViajesFacade getFacade() {
        return ejbFacade;
    }

    public Viajes prepareCreate() {
        selected = new Viajes();
        initializeEmbeddableKey();
        return selected;
    }

    public void create() {
        persist(PersistAction.CREATE, ResourceBundle.getBundle("/Bundle").getString("ViajesCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void update() {
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/Bundle").getString("ViajesUpdated"));
    }

    public void destroy() {
        if (selected == null) {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Advertencia!", "Seleccione un camión de la lista"));
        } else {
            persist(PersistAction.DELETE, ResourceBundle.getBundle("/Bundle").getString("ViajesDeleted"));
            if (!JsfUtil.isValidationFailed()) {
                selected = null; // Remove selection
                items = null;    // Invalidate list of items to trigger re-query.
            }
        }
    }

    public String statusViaje(int tipo) {
        switch (tipo) {
            case 1:
                return "En curso";
            case 2:
                return "En espera";
            default:
                return "Desconocido";
        }
    }

    public List<Viajes> getItems() {
        if (items == null) {
            items = getFacade().findAll();
        }
        return items;
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                } else {
                    getFacade().remove(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            }
        }
    }

    public Viajes getViajes(java.lang.Integer id) {
        return getFacade().find(id);
    }

    public List<Viajes> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<Viajes> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass = Viajes.class)
    public static class ViajesControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            ViajesController controller = (ViajesController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "viajesController");
            return controller.getViajes(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Viajes) {
                Viajes o = (Viajes) object;
                return getStringKey(o.getIdViaje());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), Viajes.class.getName()});
                return null;
            }
        }

    }

}

Proyecto/CamionesFrame/web/admin/viajes/camionViaje/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="CamionViajeCreateDlg" widgetVar="CamionViajeCreateDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.CreateCamionViajeTitle}">
            <h:form id="CamionViajeCreateForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{camionViajeController.selected != null}">
                        <p:outputLabel value="#{bundle.CreateCamionViajeLabel_idCamionViaje}" for="idCamionViaje" />
                        <p:inputText id="idCamionViaje" value="#{camionViajeController.selected.idCamionViaje}" title="#{bundle.CreateCamionViajeTitle_idCamionViaje}" required="true" requiredMessage="#{bundle.CreateCamionViajeRequiredMessage_idCamionViaje}"/>
                        <p:outputLabel value="#{bundle.CreateCamionViajeLabel_idViaje}" for="idViaje" />
                        <p:selectOneMenu id="idViaje" value="#{camionViajeController.selected.idViaje}" >
                            <f:selectItems value="#{viajesController.itemsAvailableSelectOne}"
                                           var="idViajeItem"
                                           itemValue="#{idViajeItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.CreateCamionViajeLabel_idCamion}" for="idCamion" />
                        <p:selectOneMenu id="idCamion" value="#{camionViajeController.selected.idCamion}" >
                            <f:selectItems value="#{camionesController.itemsAvailableSelectOne}"
                                           var="idCamionItem"
                                           itemValue="#{idCamionItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{camionViajeController.create}" value="#{bundle.Save}" update="display,:CamionViajeListForm:datalist,:growl" oncomplete="handleSubmit(args,'CamionViajeCreateDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="CamionViajeCreateDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

Proyecto/CamionesFrame/web/admin/viajes/camionViaje/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="CamionViajeEditDlg" widgetVar="CamionViajeEditDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.EditCamionViajeTitle}">
            <h:form id="CamionViajeEditForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{camionViajeController.selected != null}">
                        <p:outputLabel value="#{bundle.EditCamionViajeLabel_idCamionViaje}" for="idCamionViaje" />
                        <p:inputText id="idCamionViaje" value="#{camionViajeController.selected.idCamionViaje}" title="#{bundle.EditCamionViajeTitle_idCamionViaje}" required="true" requiredMessage="#{bundle.EditCamionViajeRequiredMessage_idCamionViaje}"/>
                        <p:outputLabel value="#{bundle.EditCamionViajeLabel_idViaje}" for="idViaje" />
                        <p:selectOneMenu id="idViaje" value="#{camionViajeController.selected.idViaje}" >
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{viajesController.itemsAvailableSelectOne}"
                                           var="idViajeItem"
                                           itemValue="#{idViajeItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.EditCamionViajeLabel_idCamion}" for="idCamion" />
                        <p:selectOneMenu id="idCamion" value="#{camionViajeController.selected.idCamion}" >
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{camionesController.itemsAvailableSelectOne}"
                                           var="idCamionItem"
                                           itemValue="#{idCamionItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{camionViajeController.update}" value="#{bundle.Save}" update="display,:CamionViajeListForm:datalist,:growl" oncomplete="handleSubmit(args, 'CamionViajeEditDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="CamionViajeEditDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

Proyecto/CamionesFrame/web/admin/viajes/camionViaje/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">


        <ui:define name="title">
            <h:outputText value="#{bundle.ListCamionViajeTitle}"></h:outputText>
        </ui:define>

        <ui:define name="body">
            <h:form id="CamionViajeListForm">
                <p:panel header="#{bundle.ListCamionViajeTitle}">
                    <p:dataTable id="datalist" value="#{camionViajeController.items}" var="item"
                                 selectionMode="single" selection="#{camionViajeController.selected}"
                                 paginator="true"
                                 rowKey="#{item.idCamionViaje}"
                                 rows="10"
                                 rowsPerPageTemplate="10,20,30,40,50"
                                 >

                        <p:ajax event="rowSelect"   update="createButton viewButton editButton deleteButton"/>
                        <p:ajax event="rowUnselect" update="createButton viewButton editButton deleteButton"/>

                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListCamionViajeTitle_idCamionViaje}"/>
                            </f:facet>
                            <h:outputText value="#{item.idCamionViaje}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListCamionViajeTitle_idViaje}"/>
                            </f:facet>
                            <h:outputText value="#{item.idViaje}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListCamionViajeTitle_idCamion}"/>
                            </f:facet>
                            <h:outputText value="#{item.idCamion}"/>
                        </p:column>
                        <f:facet name="footer">
                            <p:commandButton id="createButton" icon="ui-icon-plus"   value="#{bundle.Create}" actionListener="#{camionViajeController.prepareCreate}" update=":CamionViajeCreateForm" oncomplete="PF('CamionViajeCreateDialog').show()"/>
                            <p:commandButton id="viewButton"   icon="ui-icon-search" value="#{bundle.View}" update=":CamionViajeViewForm" oncomplete="PF('CamionViajeViewDialog').show()" disabled="#{empty camionViajeController.selected}"/>
                            <p:commandButton id="editButton"   icon="ui-icon-pencil" value="#{bundle.Edit}" update=":CamionViajeEditForm" oncomplete="PF('CamionViajeEditDialog').show()" disabled="#{empty camionViajeController.selected}"/>
                            <p:commandButton id="deleteButton" icon="ui-icon-trash"  value="#{bundle.Delete}" actionListener="#{camionViajeController.destroy}" update=":growl,datalist" disabled="#{empty camionViajeController.selected}"/>
                        </f:facet>
                    </p:dataTable>
                </p:panel>
            </h:form>

            <ui:include src="Create.xhtml"/>
            <ui:include src="Edit.xhtml"/>
            <ui:include src="View.xhtml"/>
        </ui:define>
    </ui:composition>

</html>

Proyecto/CamionesFrame/web/admin/viajes/camionViaje/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="CamionViajeViewDlg" widgetVar="CamionViajeViewDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.ViewCamionViajeTitle}">
            <h:form id="CamionViajeViewForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{camionViajeController.selected != null}">
                        <h:outputText value="#{bundle.ViewCamionViajeLabel_idCamionViaje}"/>
                        <h:outputText value="#{camionViajeController.selected.idCamionViaje}" title="#{bundle.ViewCamionViajeTitle_idCamionViaje}"/>
                        <h:outputText value="#{bundle.ViewCamionViajeLabel_idViaje}"/>
                        <h:outputText value="#{camionViajeController.selected.idViaje}" title="#{bundle.ViewCamionViajeTitle_idViaje}"/>
                        <h:outputText value="#{bundle.ViewCamionViajeLabel_idCamion}"/>
                        <h:outputText value="#{camionViajeController.selected.idCamion}" title="#{bundle.ViewCamionViajeTitle_idCamion}"/>
                    </p:panelGrid>
                    <p:commandButton value="#{bundle.Close}" onclick="CamionViajeViewDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>